# -*- coding: utf-8 -*- 
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mkBKvKyxhrKLWjWwCeEpiXW7u_sr4TQ
"""

# app.py

from pdfminer.high_level import extract_text
import re
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForCausalLM
# ----------------------------------------
# 1. Leer y limpiar el texto del PDF
# ----------------------------------------

pdf_path = "LUC.pdf"
text = extract_text(pdf_path)

def clean_text(text):
    cleaned = text.replace('\n', ' ')
    cleaned = ' '.join(cleaned.split())
    return cleaned

cleaned_text = clean_text(text)

# ----------------------------------------
# 2. Chunking por artículo
# ----------------------------------------

def chunk_by_article(text):
    matches = list(re.finditer(r"\bArtículo\s+\d+\b", text))
    print(f"Se encontraron {len(matches)} artículos.")
    chunks = []
    for i in range(len(matches)):
        start = matches[i].start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        chunk = text[start:end].strip()
        chunks.append(chunk)
    return chunks

chunks = chunk_by_article(cleaned_text)
print(f"{len(chunks)} chunks generados.")

# ----------------------------------------
# 3. Embeddings + FAISS
# ----------------------------------------

embedder = SentenceTransformer("intfloat/e5-base")
embeddings = embedder.encode(
    [f"passage: {chunk}" for chunk in chunks],
    show_progress_bar=True
)

embedding_array = np.array(embeddings)
index = faiss.IndexFlatL2(embedding_array.shape[1])
index.add(embedding_array)
print(f"Índice FAISS creado con {index.ntotal} vectores.")

# ----------------------------------------
# 4. Función para recuperar contexto relevante
# ----------------------------------------

def retrieve_context(pregunta, k=3):
    query_embedding = embedder.encode([f"query: {pregunta}"])
    distances, indices = index.search(np.array(query_embedding), k)
    retrieved_chunks = [chunks[i] for i in indices[0]]
    return "\n\n---\n\n".join(retrieved_chunks)

# ----------------------------------------
# 5. Carga del modelo LLaMA 3.2–1B
# ----------------------------------------

model_id = "meta-llama/Llama-3.2-1B"
tokenizer = AutoTokenizer.from_pretrained(model_id, use_auth_token="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")
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype="auto",
    use_auth_token="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"
)
# ----------------------------------------
# 6. Función de respuesta final
# ----------------------------------------

def responder_llm(pregunta, k=3, max_tokens=512):
    contexto = retrieve_context(pregunta, k)

    prompt = f"""
Actuá como un abogado especializado en la Ley de Urgente Consideración (LUC) de Uruguay. Respondé con precisión y brevedad usando exclusivamente el texto legal proporcionado.

No inventes información.
No formules nuevas preguntas.
Si no hay información suficiente, respondé:
"No se encuentra información suficiente en la ley proporcionada."

---

Fragmento de la ley:
{contexto}

Pregunta: {pregunta}
Respuesta:"""

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=max_tokens,
        do_sample=True,
        temperature=0.05
    )
    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
    respuesta = decoded.replace(prompt, "").strip().split("Pregunta:")[0].strip()
    return respuesta

# ----------------------------------------
# 7. Prueba local
# ----------------------------------------

if __name__ == "__main__":
    pregunta = "¿Qué dice la ley sobre el chorizo artesanal?"
    print(responder_llm(pregunta))

    pregunta = "¿Qué dice la ley sobre los allanamientos nocturnos?"
    print(responder_llm(pregunta))